{
 "title": "MYAPP DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_count_total[2m]))"
    }
   ]
  },
  {
   "title": "RPS error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_error_count_total[2m]))"
    }
   ]
  },
  {
   "title": "Latency with quantile 0.5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le) (rate(http_server_requests_seconds_bucket[1m]))))"
    }
   ]
  },
  {
   "title": "Latency with quantile 0.95",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (le) (rate(http_server_requests_seconds_bucket[1m]))))"
    }
   ]
  },
  {
   "title": "Latency with quantile 0.99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (sum by (le) (rate(http_server_requests_seconds_bucket[1m]))))"
    }
   ]
  },
  {
   "title": "Latency with quantile 1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, (sum by (le) (rate(http_server_requests_seconds_bucket[1m]))))"
    }
   ]
  },
  {
   "title": "Status 500",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{status=~\"5.+\"}[2m]))"
    }
   ]
  },
  {
   "title": "Used memory by pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{pod=~\"homeworkapp.+\"}) by (pod))/(1024*1024)"
    }
   ]
  },
  {
   "title": "Used memory by pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"homework.+\"}[2m]))"
    }
   ]
  }
 ]
}