{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "homeworkhelm.fullname" . }}
  labels:
    {{- include "homeworkhelm.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "homeworkhelm.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "homeworkhelm.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: web
      path: /actuator/prometheus
  {{- end }}