server:
  port: 8000

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/TestDB"
    username: "postgres"
    password: "postgres"
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: changelog.xml
    default-schema: "public"
    enabled: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: prometheus,health
  endpoint:
    prometheus.enabled: true
    health.enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
