apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 8000
  selector:
    app: myapp
  type: ClusterIP
