apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homework-chart.fullname" . }}
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "homework-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homework-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: homework-config
            - secretRef:
                name: homework-secret
