apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: order-service
    context: .
deploy:
  helm:
    releases:
    - name: order-service
      chartPath: homework-chart
      skipBuildDependencies: true
      values:
        image: order-service
